Fix Pipeline to recognize errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,8 +29,14 @@ jobs:
         cd BentoContainerManager
         dotnet build
         dotnet publish -c Release -o publish
+        cp ../BentoConfiguration.json publish/
 
     - name: Run Container and Tests
       run: |
         cd BentoContainerManager/publish
         ./BentoContainerManager up
+        if [ $? -ne 0 ]; then
+          echo "Container manager failed"
+          exit 1
+        fi
+      shell: bash
